# Generated by Django 4.2.10 on 2025-05-15 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='utilisateur',
            field=models.OneToOneField(help_text='Compte utilisateur Django associé à cet administrateur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrateur', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur associé'),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='utilisateurs',
            field=models.ManyToManyField(blank=True, help_text='Ancien champ - ne pas utiliser', related_name='administrateurs', to=settings.AUTH_USER_MODEL, verbose_name='Comptes utilisateurs associés (legacy)'),
        ),
    ]
