# Generated by Django 5.2 on 2025-05-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("objectifs", models.JSONField(default=list)),
                ("programme", models.JSONField(default=list)),
                ("prerecquis", models.JSONField(default=list)),
                ("acquis", models.TextField(verbose_name="acquis")),
                ("debouche", models.TextField(verbose_name="Débouchés")),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("lieu", models.CharField(max_length=100)),
            ],
        ),
    ]
